export default function Head() {
  return (
    <>
      <title>Panaverse DAO</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by Panaverse DAO' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
